### PR TITLE
✨ Use Curator for rxrx ingestion

### PR DESCRIPTION
**Pull request by Zethson**
Fixes https://github.com/laminlabs/lamin-spatial/issues/29

- Refactors the rxrx-ingest guide to use the Pandas `DataFrame` curator & simplifies it further
- Switches CI to Python 3.12 & reenables docs building CI again

### CODE REVIEW

**Comment by falexwolf** [comment]
This looks better! :D 

Can you please use strikt/ non-hanging indendation?

image

I suggest we remove everything that's not absolutely necessary for this curation so that it becomes as streamlined as possible. We don't need to show hierarchical ontologies etc.

**Comment by falexwolf** [comment]
Today we'd call `is_well_type` just `well_type` for simplicity across the docs without tremendous downsides.

But I wonder whether we even still need this? Also, what about the `Well` registry in `wetlab`? @sunnyosun 

image

**Comment by Zethson** [comment]
I polished it further and it's ready now. However it does not run on `lamindata`. See: https://laminlabs.slack.com/archives/C07DB677JF6/p1733739524764029?thread_ts=1733310906.230129&cid=C07DB677JF6

**Comment by Zethson** [comment]
I am merging this now as is and as soon as the notebook runs through with `lamindata`, I will add a link to the rxrx notebook as discussed.

**Pull request merged**
